---
- name: Configure and verify NTP on Cisco devices
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Configure NTP server
      cisco.ios.ios_config:
        lines:
          - "ntp server {{ ntp_server }}"

    - name: Verify NTP server configuration
      cisco.ios.ios_command:
        commands: "show run | inc ntp server"
      register: ntp_config_output

    - name: Display NTP server configuration
      debug:
        var: ntp_config_output.stdout_lines
